package EMR.Doctor;

import java.time.Duration;
import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class A_SearchPatient_Visit_Phase_Page {

	public static void main(String[] args) throws InterruptedException {
		// TODO Auto-generated method stub

		// ******************Launch Browser*****************

		// Launch Chrome Browser
		System.setProperty("webdriver.chrome.driver",
				"C:\\Users\\AKDNdHRC\\Selenium\\Training Sessions\\Session 01\\MavenLoginTest\\Login\\chromedriver\\chromedriver.exe");

		WebDriver driver = new ChromeDriver();

		// Explicit Wait for 60 Seconds [Specific WebElement]
		WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(60));

		// Implicit Wait for 60 Seconds [Global use for All WebElement]
		driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
		driver.manage().timeouts().scriptTimeout(Duration.ofSeconds(30));
		driver.manage().timeouts().pageLoadTimeout(Duration.ofSeconds(60));

		// **********************Open Browser****************

		// Browser Open in Maximise Windowy
		driver.manage().window().maximize();

		// Open URL EMR Staging Site (Login Page)
		driver.get("https://emrdoctor.virtualdoc.akdndhrc.org/#/emrfrontend/");

		// *********************Login Page********************

		// Pauses for 2 second
		Thread.sleep(2000);

		// Locate User name By CSS Locator -- [tag#id] -- CSS Locator # 01
		driver.findElement(By.cssSelector("input#mat-input-0")).sendKeys("sabeen.shah@aku.edu");

		// Locate Password by By CSS Locator -- (tag[attribute=value]) -- CSS Locator #
		// 03
		driver.findElement(By.cssSelector("input[type=password]")).sendKeys("sabeen123#");

		// Locate Login Button by CSS Locator using [tag.value of class name] -- CSS
		// Locator # 02
		driver.findElement(By.cssSelector("button.btn-Signin")).click();

		// Flow
		System.out.println("Step# 01: Successfully Login the EMR Doctor App.");

		// *******************Dashboard************************

		// In Dashboard Click on "Search Patient" Button

		// Pauses for 4 second
		Thread.sleep(4000);

		// Locate Snack-Br (Toast Message) and Press Ok Button
		driver.findElement(By.xpath("//div[@aria-live='assertive']//div//simple-snack-bar//div//button")).click();

		// Locate Search Patient Button by Xpath
		driver.findElement(By.xpath("//button[normalize-space()='Search Patient']")).click();

		// Flow
		System.out.println("Step# 02: In Dashboard Click on 'SEARCH PATIENT' Button ");

		// *********************Search Patient******************

		// Pauses for 1 second
		Thread.sleep(1000);

//		// Search Fields
		// Appt. Date: dd-MM-yyyy
		String Appt_Date = "01-01-2024";
		// ______________________________________________________

		// Search Criteria in Search Patient Screen

//		// Field #01 Patient Name [User Input]
//		String Patient_Name = "Test Patient Two";

		// Field #02 MR No [Auto-Generated by App]
		String Patient_MR_No = "1660065";

		// Field #03 AKU MR No [User Input]
//				String Patient_AKU_MR_No = "777-71-55";

		// Field #04 CNIC No [User Input]
//				String Patient_CNIC_No = "02286309891129";

		// Field #05 Phone No [User Input]
//				String Patient_Phone_No = "03128866445";

//				// Locate User name By XPath Locator
//				driver.findElement(By.xpath(
//						"/html/body/app-root/app-search-patient/div/mat-card/form/div[1]/div[1]/mat-form-field/div/div[1]/div[3]/input"))
//						.sendKeys(Patient_Name);

		// Locate MR No By XPath Locator
		driver.findElement(By.xpath(
				"/html/body/app-root/app-search-patient/div/mat-card/form/div[1]/div[2]/mat-form-field/div/div[1]/div[3]/input"))
				.sendKeys(Patient_MR_No);

//								// Locate AKU MR No By XPath Locator
//								driver.findElement(By.xpath(
//										"/html/body/app-root/app-search-patient/div/mat-card/form/div[1]/div[3]/mat-form-field/div/div[1]/div[3]/input"))
//										.sendKeys(Patient_AKU_MR_No);
		//
//								// Locate CNIC No By XPath Locator
//								driver.findElement(By.xpath(
//										"/html/body/app-root/app-search-patient/div/mat-card/form/div[1]/div[4]/mat-form-field/div/div[1]/div[3]/input"))
//										.sendKeys(Patient_CNIC_No);
		//
//								// Locate Phone No By XPath Locator
//								driver.findElement(By.xpath(
//										"/html/body/app-root/app-search-patient/div/mat-card/form/div[1]/div[5]/mat-form-field/div/div[1]/div[3]/input"))
//										.sendKeys(Patient_Phone_No);
		//
		// Locate Search Button by XPath
		driver.findElement(By.xpath("/html/body/app-root/app-search-patient/div/mat-card/form/div[2]/button[1]"))
				.click();

		// Flow
		System.out.println("Step# 03: Successfully Searched the Patient Whose MR No. is [ " + Patient_MR_No + " ]");
//		System.out.println("Step# 03: Successfully Searched the Patient Whose Name is [ " + Patient_Name + " ]");
//		System.out.println("Step# 03: Successfully Searched the Patient Whose AKU MR No. is [ " + Patient_AKU_MR_No + " ]");

		// *********************Select Patient******************

		// Pauses for 3 seconds
		Thread.sleep(3000);

		// In Select Patient Screen to Find Patient With MR No and Appt. Date then
		// Select

		try {

			// Define Search Criteria
			String Patient_searchByMrNo = Patient_MR_No; // Patient MR No
			String Patient_searchByApptDate = Appt_Date; // Patient Appt. Date

			// Flow
			System.out.println("Step# 04: Select Patient With Appt. Date: [ " + Appt_Date
					+ " ] Regardless of Whether the Appt. has Ended or Not ");

			boolean Patientfound = false;

			// Define XPaths
			String patientMRXPath = ".//table//th[contains(text(), 'MR No')]/following-sibling::td";
			String ApptDateXPath = ".//table//th[contains(text(), 'Appointment Date')]/following-sibling::td";
			String SelectButtonXPath = ".//button[contains(@class,'Select')]";

			// Find all Patient Cards
			List<WebElement> VHpatientCards = driver
					.findElements(By.xpath("//mat-card[contains(@class, 'mat-focus-indicator')]"));

			// Loop Through Cards to Find a Match
			for (WebElement VHcard : VHpatientCards) {
				String patientMR = VHcard.findElement(By.xpath(patientMRXPath)).getText().trim();
				String ApptDate = VHcard.findElement(By.xpath(ApptDateXPath)).getText().trim();

				// Check if this Card Matches Exact Search Criteria
				if (patientMR.equalsIgnoreCase(Patient_searchByMrNo)
						&& ApptDate.equalsIgnoreCase(Patient_searchByApptDate)) {

					// Extract the patient name
					String PatientName = VHcard.findElement(By.xpath(".//p[contains(@class, 'patientName-Txt')]"))
							.getText().trim();

					// Click the View pdf Button
					WebElement SelectButton = wait.until(
							ExpectedConditions.elementToBeClickable(VHcard.findElement(By.xpath(SelectButtonXPath))));
					SelectButton.click();

					System.out.println("Step# 05: Selected Patient With Name: [ " + PatientName + " ] With MR No: [ "
							+ Patient_MR_No + " ] OR Appt. Date [ " + Appt_Date + " ]");

					System.out.println("Step# 06: Detailed View Phase Page for The Patient With Name: [ " + PatientName
							+ " ] With MR No: [ " + Patient_MR_No + " ] OR Appt. Date [ " + Appt_Date + " ]");

					Patientfound = true;
					break; // Stop after first match

				}
			}

			if (!Patientfound) {
				System.out.println("Step# 05: No Patient Found with Appt. Date: [ " + Appt_Date + " ]");

			}

		} catch (Exception e) {
			System.out.println("Exception Occurred: " + e.getMessage());
		}

		// ******************Patient Phase Page******************

		// Patient Phase Page Detailed View Patient Profile Tab

		// Pauses for 3 seconds
		Thread.sleep(3000);

		// View Problem List Tab
		driver.findElement(By.xpath("//button[normalize-space()='Problem List']")).click();
		System.out.println("Step# 07: In Phase Page Clicked on 'PROBLEM LIST' Tab  For View");

		// Pauses for 3 seconds
		Thread.sleep(3000);

		// View Medication Tab
		driver.findElement(By.xpath("//button[normalize-space()='Medication']")).click();
		System.out.println("Step# 08: In Phase Page Clicked on 'MEDICATION' Tab  For View");

		// Pauses for 3 seconds
		Thread.sleep(3000);

		// View Allergy Tab
		driver.findElement(By.xpath("//button[normalize-space()='Allergy']")).click();
		System.out.println("Step# 09: In Phase Page Clicked on 'ALLERGY' Tab  For View");

		// Pauses for 3 seconds
		Thread.sleep(3000);

		// View Immunization Tab
		driver.findElement(By.xpath("//button[normalize-space()='Immunization']")).click();
		System.out.println("Step# 10: In Phase Page Clicked on 'IMMUNIZATION' Tab  For View");

		// Pauses for 3 seconds
		Thread.sleep(3000);

		// View Investigation Result Tab
		driver.findElement(By.xpath("//button[normalize-space()='Investigation Result']")).click();
		System.out.println("Step# 11: In Phase Page Clicked on 'INVESTIGATION RESULT' Tab  For View");

		// Pauses for 3 seconds
		Thread.sleep(3000);

		// View Uploaded Document Tab
		driver.findElement(By.xpath("//button[normalize-space()='Upload Documents']")).click();
		System.out.println("Step# 12: In Phase Page Clicked on 'UPLOAD DOCUMENTS' Tab  For View");

		// Pauses for 3 seconds
		Thread.sleep(3000);

		// View Personal History Tab
		driver.findElement(By.xpath(" //button[normalize-space()='Personal Social History']")).click();
		System.out.println("Step# 13: In Phase Page Clicked on 'PERSONAL HISTORY' Tab  For View");

		// Patient Phase Page Detailed View Patient Demographics Tab

		// Pauses for 3 seconds
		Thread.sleep(3000);

		// View Patient Demographics Tab
		driver.findElement(By.xpath("//a[normalize-space()='DEMOGRAPHICS']")).click();
		System.out.println("Step# 14: In Phase Page Clicked on 'PATIENT DEMOGRAPHICS' Tab  For View");

		// Patient Phase Page Detailed View Patient Visit History Tab

		// Pauses for 3 seconds
		Thread.sleep(3000);

		// View Patient Visit History Tab
		driver.findElement(By.xpath("//a[normalize-space()='Visit History']")).click();
		System.out.println("Step# 15: In Phase Page Clicked on 'PATIENT VISIT HISTORY' Tab  For View");
		
		System.out.println(" 👍 Happy Flow ദ്ദി˙ ᴗ ˙ )");


	}
}
